"""Convert connector to array

Revision ID: a3a7dfc8f8a0
Revises: abb11ee460e1
Create Date: 2025-11-24 14:43:50.559382

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a3a7dfc8f8a0"
down_revision: Union[str, Sequence[str], None] = "abb11ee460e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("connectors")
    op.add_column(
        "cars",
        sa.Column(
            "connector_types",
            sa.ARRAY(
                sa.Enum("Type 2", "Schuko", "CCS", "CHAdeMO", name="connectortype")
            ),
            nullable=False,
        ),
    )
    op.create_unique_constraint(None, "users", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'users', type_='unique')
    op.drop_column("cars", "connector_types")
    op.create_table(
        "connectors",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM("Type 2", "Schuko", "CCS", "CHAdeMO", name="connectortype"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("car_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["car_id"], ["cars.id"], name=op.f("connectors_car_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("connectors_pkey")),
    )
    # ### end Alembic commands ###
